In [0]:
import pandas as pd

In [0]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [0]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [30]:
wine = pd.read_csv('https://github.com/nahidhasan98/recycle/blob/master/movies.csv')
wine

ParserError: ignored

In [31]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

E: Package 'python-software-properties' has no installation candidate
Selecting previously unselected package google-drive-ocamlfuse.
(Reading database ... 145605 files and directories currently installed.)
Preparing to unpack .../google-drive-ocamlfuse_0.7.14-0ubuntu1~ubuntu18.04.1_amd64.deb ...
Unpacking google-drive-ocamlfuse (0.7.14-0ubuntu1~ubuntu18.04.1) ...
Setting up google-drive-ocamlfuse (0.7.14-0ubuntu1~ubuntu18.04.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive

In [37]:
%cd drive/

[Errno 2] No such file or directory: 'drive/'
/content/drive

In [38]:
%ls

'Blogger Downloads Item'/   Extras/                         Worksheet2016april/
'Colab Notebooks'/         'Hard Drive'/
 diabetes2.csv             'System Analysis Survey Form'/

In [50]:
df = pd.read_csv("diabetes2.csv")
df.head(10)

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1
5            5      116             74  ...                     0.201   30        0
6            3       78             50  ...                     0.248   26        1
7           10      115              0  ...                     0.134   29        0
8            2      197             70  ...                     0.158   53        1
9            8      125             96  ...                     0.232   54        1

[10 rows x 9 columns]

In [67]:
df = pd.read_csv("diabetes2.csv")
df[6:15]

    Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
6             3       78             50  ...                     0.248   26        1
7            10      115              0  ...                     0.134   29        0
8             2      197             70  ...                     0.158   53        1
9             8      125             96  ...                     0.232   54        1
10            4      110             92  ...                     0.191   30        0
11           10      168             74  ...                     0.537   34        1
12           10      139             80  ...                     1.441   57        0
13            1      189             60  ...                     0.398   59        1
14            5      166             72  ...                     0.587   51        1

[9 rows x 9 columns]

In [179]:
tf = pd.read_csv("test (a0e4320a).csv")
tf.iloc[0]['Gender']

'Male'

In [178]:
%ls

'Blogger Downloads Item'/  'System Analysis Survey Form'/
'Colab Notebooks'/         'test (a0e4320a).csv'
 diabetes2.csv             'test (fd8e4823).csv'
 Extras/                    Worksheet2016april/
'Hard Drive'/

In [72]:
df.loc[df.index[9:23],['BMI','Glucose']]

     BMI  Glucose
9    0.0      125
10  37.6      110
11  38.0      168
12  27.1      139
13  30.1      189
14  25.8      166
15  30.0      100
16  45.8      118
17  29.6      107
18  43.3      103
19  34.6      115
20  39.3      126
21  35.4       99
22  39.8      196

In [77]:
df.iloc[:,0]

0       6
1       1
2       8
3       1
4       0
       ..
763    10
764     2
765     5
766     1
767     1
Name: Pregnancies, Length: 768, dtype: int64

In [182]:
counter = 0
#x = 0
size = tf.shape[0]

for x in range(size):
  tmp = tf.loc[x,'Gender']
  if tmp == 'Female':
    counter+=1

print(counter)

2

In [190]:
tf.loc[(tf.Country == 'Bangladesh') & (tf.Gender == 'Male')]

    Name Gender     Country
0  Nahid   Male  Bangladesh

In [192]:
tf.loc[tf.Country.isin(['Bangladesh', 'London'])]

    Name  Gender     Country
0  Nahid    Male  Bangladesh
1  Julia  Female      London
2      a    Male      London
3      a  Female      London
4      a    Male      London

In [198]:
tf.Name.value_counts()

a        3
Nahid    1
Julia    1
Name: Name, dtype: int64

In [199]:
tf.Country + "/" + tf.Gender

0    Bangladesh/Male
1      London/Female
2        London/Male
3      London/Female
4        London/Male
dtype: object

In [200]:
tf[pd.isnull(tf.Gender)]

Empty DataFrame
Columns: [Name, Gender, Country]
Index: []

In [201]:
pd.concat([df,tf])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

     Age   BMI  BloodPressure  ... Outcome  Pregnancies SkinThickness
0   50.0  33.6           72.0  ...     1.0          6.0          35.0
1   31.0  26.6           66.0  ...     0.0          1.0          29.0
2   32.0  23.3           64.0  ...     1.0          8.0           0.0
3   21.0  28.1           66.0  ...     0.0          1.0          23.0
4   33.0  43.1           40.0  ...     1.0          0.0          35.0
..   ...   ...            ...  ...     ...          ...           ...
0    NaN   NaN            NaN  ...     NaN          NaN           NaN
1    NaN   NaN            NaN  ...     NaN          NaN           NaN
2    NaN   NaN            NaN  ...     NaN          NaN           NaN
3    NaN   NaN            NaN  ...     NaN          NaN           NaN
4    NaN   NaN            NaN  ...     NaN          NaN           NaN

[773 rows x 12 columns]

In [202]:
join = df.join(tf)
join

     Pregnancies  Glucose  BloodPressure  ...   Name  Gender     Country
0              6      148             72  ...  Nahid    Male  Bangladesh
1              1       85             66  ...  Julia  Female      London
2              8      183             64  ...      a    Male      London
3              1       89             66  ...      a  Female      London
4              0      137             40  ...      a    Male      London
..           ...      ...            ...  ...    ...     ...         ...
763           10      101             76  ...    NaN     NaN         NaN
764            2      122             70  ...    NaN     NaN         NaN
765            5      121             72  ...    NaN     NaN         NaN
766            1      126             60  ...    NaN     NaN         NaN
767            1       93             70  ...    NaN     NaN         NaN

[768 rows x 12 columns]